asdf-vm/asdf-ruby

bin/install

A couple of popular Gems (Pry, Guard) do not function properly without using GNU readline (e.g. [this GitHub Issue](https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X)).
This patch checks to see if GNU Readline has been installed via Homebrew on the Mac OS X and adds the proper `configure` argument. I don't *think* this is an issue on Linux because GNU Readline seems to be the default there.
I don't think it's worthwhile to make this a required Homebrew package like libyaml and libssl, but it certainly could be. For what it's worth, `ruby-build` takes this same approach of optionally using readline if it's installed.

Use GNU Readline if it's available

---

bin/install
bin/list-all

I've notices that I can install `2.4.0-preview3` but it's not on the list. Now list is downloaded directly from server. JRuby is an exception, is still a static list.

Download all versions of ruby from servers

---

bin/exec-env

[This issue comment](https://github.com/asdf-vm/asdf/issues/64#issuecomment-261809489) perfectly describes the issue.
As per the linked comment, this change implements the suggested fix to prepend the install path to the `PATH` environment variable.
I ran into this issue when migrating from `rbenv` to `asdf`. My Ruby linter stopped working in Sublime Text.
Before I made the change, this is the debug trace from Sublime Text when trying to execute the linter, in this case `rubocop`:
```
SublimeLinter: ENV['GEM_HOME'] = 'None' 
Package Control: No updated packages
SublimeLinter: rubocop version query: /Users/ed/.asdf/shims/ruby -S rubocop --version 
SublimeLinter: rubocop version: 2.3.1 
SublimeLinter: rubocop: (>= 0.34.0) satisfied by 2.3.1 
SublimeLinter: rubocop activated: …
```

include current Ruby install path in PATH

---

README.md
bin/install

https://github.com/asdf-vm/asdf-ruby/issues/31

Add support for a default-gems file

---

README.md
bin/install

My preliminary testing is done, but I will give it a more thorough spin tomorrow. In the meantime, please take a look. If you see a better way to resolve relative paths, that'd be nice. The patch introduces a couple of new dependencies: `grep`, `patch` and it requires a Bash 3+ something, due to the regex operator.
Cheers
Stefan

allow to apply custom patches during install (fixes #15)

---

bin/install

Good hint about `$ASDF_CONCURRENCY`, it makes this much simpler than anticipated!

use available CPU cores when compiling (fixes #42)

---

README.md

Using `mv -T` allows `~/.rbenv/versions` to rename to `~/.asdf/installs/ruby` instead of ending up with `~/.asdf/installs/ruby/versions` (default behavior of `mv` without `-T`)

Update doc: use `mv -T` to move rbenv rubies to asdf rubies

---

README.md
bin/exec-env
bin/get-version-from-legacy-file
bin/install
bin/list-all
lib/utils.sh

@Stratus3D After our discussion in #38 I started working on integrating ruby-build into asdf-ruby. Everything seems to be working fine but this obviously needs some extensive testing and is still at an early stage. For now I've just manually tested the commands under macOS.
I realize that this is a rather drastic change in direction for this project but I think it does not make much sense to try and keep up with the latest Ruby versions, platforms etc. when we can use another project that is already doing a good job at this.
One open question is whether we want to leave it up to the user to install `ruby-build` themselves or have our own copy inside asdf-ruby. If we include it we also need to keep it up to date and so on, otherwise we can rely on OS package managers to do the work for us. …

Use ruby-build

---

bin/install

`get_absolute_path` is called with the patch file path as the first
argument.
This commit fixes the relative path reference in the function to use
the value of the first argument passed into it.

Fix patch relative path reference

---

bin/get-version-from-legacy-file

Newer versions of Rails is pre-baked to have `ruby-x.x.x` in the `.ruby-version` file.
This breaks the legacy support as the whole contents of the file is used as the ruby version.
This PR adds a filtering when getting the legacy version from the file (remove `ruby-` prefix if it exists).

Fix #69 - Filter out 'ruby-' in .ruby-version file

---

bin/parse-legacy-file

This updates asdf-ruby to use the new `parse-legacy-file` script. It was previously ignoring the legacy version file since it was never calling this script.
Fixes #84

Fix deprecated legacy version file parsing

---

bin/install

you know how bundler 2 just came out and doesn't work with old ruby versions? this will hopefully lessen the consternation around this by allowing folks to opt in to a specific version of gems in their asdf-ruby .default-versions file.
here's my old one:
~ % cat .default-gems
bundler
and my new one:
~ % cat .default-gems
bundler 1.17.3
both are now supported.
thanks a ton for maintaining asdf-ruby! have you considered using the ruby-install project instead of ruby-build?

support desired gem versions in .default-gems

---

bin/install

It looks like with our Bash settings empty arrays are seen as unbound for some reason. By adding the `${:-}` syntax we allow for empty `gem` arguments.
Fixes #99

Allow for empty args for default gems

---

bin/install

Fixes #64 and fix absolute path resolving for local patch. I have done some preliminary test on both FreeBSD and macOS that asdf-ruby can build 2.5.1 successfully. For patching, I've check that it works by giving it a bogus patch and watch the build fail (which seems to fail properly).

Do not pass patch if no patch is provided

---

README.md

Related to https://github.com/asdf-vm/asdf/issues/352.
This PR only documents current behaviour.

Add a note about full/trimmed ruby version in legacy file

---

.travis.yml

asdf plugin-test on Travis appears failing the installation of Truffleruby on macos due to the failure of openssl recompilation.
This PR make it [skip recompiling openssl](https://github.com/oracle/truffleruby/blob/f08dd1ac65f22da9bb976ee8792429bfce6d04c5/lib/truffle/post_install_hook.sh#L23) until the issue be fixed on TruffleRuby's side (oracle/truffleruby#1417).
Thoughts?

Skip recompiling openssl for truffleruby

---

bin/list-all
lib/utils.sh

Also, use `grep -v` (-v: Invert match) to remove the `topaz-dev` from
the results.
Fixes #142.

Fix `bin/list-all`

---

lib/utils.sh

Summary:
`$RUBY_BUILD_VERSION` is actually tag name, it starts with `v`, for example `v20190828`, and it always be different with version that is parsed from `ruby-build --version`. Because of this, `asdf list-all ruby` or `asdf install ruby` always trigger re-downloading `ruby-build` source.
```bash
asdf-ruby (master) $ ~/.asdf/plugins/ruby/ruby-build/bin/ruby-build --version
ruby-build 20190828
asdf-ruby (master) $ ~/.asdf/plugins/ruby/ruby-build/bin/ruby-build --version | cut -d ' ' -f2
20190828
```

Fix install / list-all commands always re-download ruby-build

---

bin/list-all
lib/utils.sh

We are currently hiding all output written to STDERR when running the `list-all` script. The STDERR output is useful as it is used to display info on the ruby-build download.

Fix output of `asdf list-all ruby` when downloading ruby-build

---

bin/install

This fixes #150 which happens when there's no version specified for gems in `$HOME/.default-gems` file.

Fix marshal data too short error for default gems

---

rubygems-plugin/rubygems_plugin.rb

This fixes #63 but depends on https://github.com/rubygems/rubygems/pull/3534 being merged in order to actually work. There is a long-standing bug in bundler that prevents it from loading `rubygems_plugin.rb` from `RUBYLIB`. However, there is no problem having this hook exist with a version of bundler that doesn't support it -- this file will just never be evaluated in that case.
It also fixes shims not being removed on `gem uninstall` where installer.bin_dir is not set, so it can never match `Gem.default_bindir`. Additionally, the `#{RUBY_VERSION} bin/#{executable}` syntax does not work for removing shims, so in the interest of simplicity, the hook now just runs `asdf reshim ruby` which works in both the install and uninstall cases, but is potentially less efficient for installation via …

Fix auto-reshim on bundle install and gem uninstall.

---

bin/parse-legacy-file

Fixes #116
Just ignore the Gemfile that has lines like `ruby '~> 2.6'`.

Ignore Gemfile that has not strict specification

---

README.md
bin/install

Similair to the implementations created in https://github.com/asdf-vm/asdf-nodejs/pull/170 and https://github.com/danhper/asdf-python/pull/63; which are already merged. This provides an alternative to https://github.com/asdf-vm/asdf-ruby/pull/114.

Support non-default .default-gems locations.

---

bin/parse-legacy-file

Fixes #214 
Fixes #215 
Tested using this script:
```bash
#!/usr/bin/env bash
set -euo pipefail
function cases() {
cat <<EOF
2.0.0|ruby '2.0.0'
2.0.0|ruby "2.0.0"
2.0.0|ruby("2.0.0")
2.0.0|ruby "2.0.0" # a comment
2.0.0|     ruby  "2.0.0"       ,:patchlevel         => "200
2.0.0-dev|ruby "2.0.0-dev"
|ruby "~> 2.0.0"
jruby-1.0.0|ruby '2.0.0', engine: 'jruby', engine_version: '1.0.0'
jruby-1.0.0|ruby "2.0.0", engine: "jruby", engine_version: "1.0.0"
jruby-1.0.0|ruby("2.0.0", engine: "jruby", engine_version: "1.0.0")
jruby-1.0.0|ruby "2.0.0", :engine => "jruby", :engine_version => "1.0.0"
jruby-1.0.0|ruby "2.0.0", :engine_version => "1.0.0", :engine => "jruby"
jruby-1.0.0-dev|ruby "2.0.0", :engine => "jruby", :engine_version => "1.0.0-dev"
|ruby "2.0.0", :engine => "jruby", :engine_version …
```

Improve `Gemfile` version parsing

---

bin/exec-env

`ASDF_INSTALL_PATH` is documented here: https://asdf-vm.com/plugins/create.html#environment-variables
`install_path` *does* exist, but we shouldn't rely upon its existence.
It's a local variable of an asdf function that just happens to be
calling this `exec-env` via a `.` (aka: "source") directive:
https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L571-L579.
We shouldn't rely on this implementation detail when there's a
documented alternative.

Use `ASDF_INSTALL_PATH` instead of `install_path`

---

bin/exec-env

When run under asdf-direnv with direnv's `strict_env` set to true, then
this script will run with bash's `nounset` enabled, which will cause
this script to crash in the following way:
./exec-env:6: RUBYLIB: unbound variable
(see https://github.com/asdf-community/asdf-direnv/issues/115 for
details)
I know this doesn't affect regular asdf users, but this seems like a
reasonable change to make, I hope you'll accept it!

Don't assume that the `RUBYLIB` environment variable exists

---

lib/utils.sh

It redirects again by `>/dev/null` immediately.

Remove meaningless redirect

---

bin/exec-env

The bin/exec-env command is adding $ASDF_INSTALL_PATH/bin to PATH, but asdf already does this automatically. This causes a [duplicate ruby/bin in PATH when used with the asdf-direnv plugin.](https://github.com/asdf-community/asdf-direnv/issues/148)

fix: Duplicate bin path in PATH due to exec-env setting PATH

---

.github/dependabot.yml
.github/workflows/ci.yml
.travis.yml
README.md
bin/install
bin/list-all
lib/utils.sh

Looks like the current CI is not running. At least I can't see the result link from badges.
https://blog.travis-ci.com/2021-05-07-orgshutdown
So I have replaced to GitHub Actions with https://github.com/asdf-vm/actions/blob/171cc3570019f3a69ba10ae269ab46990936fa9f/README.md instruction except integrating `shfmt`.
* New CI testing with `3.1.2` for now.
* Integrating `shfmt` made [a lot of diff](https://github.com/kachick/asdf-ruby/runs/7450394069?check_suite_focus=true), so I have omitted it.
* Basically disabled `ShellCheck` alerting in current code to keep as-is behavior.

Replace ceased travis-ci.org with GitHub Actions

---

README.md

This PR updates the project's README to explain how to update `asdf-ruby` to ensure the latest available versions of Ruby are available.
The documentation is not clear on what to do if ruby versions are missing from the global version list, and this confusion has already caused a few issues in the Github page, e.g:
https://github.com/asdf-vm/asdf-ruby/issues/302#issuecomment-1251442041
https://github.com/asdf-vm/asdf-ruby/issues/135#issuecomment-533797509
So hopefully this addition to the README provides a little clarity. :)

Update README for updating asdf-ruby for latest ruby versions

---

bin/install

Previously, if users attempted to install a new version of Ruby, they would just see "Version not found":
```shell
% asdf install ruby 2.7.7
Version not found
```
It may be useful to give a hint to the user that the plugin has to be updated:
```shell
% asdf install ruby 2.7.7
Version not found
If this is a new Ruby version, you may need to run:
asdf plugin update ruby
```

Improve "Version not found" message

---

bin/list-bin-paths

There can be the situation where the binary files of an Gem aren't installed into the common `bin` directory.
This happens when the Gem Specification is lacking the `bindir` setting.

add list-bin-paths command

---

bin/install

This PR address Issue https://github.com/asdf-vm/asdf-ruby/issues/335. Where a `.default-gems` file without a final empty line, will skip the last gem specified.
The fix is based on [SO answer](https://stackoverflow.com/a/12916758/13783004).

fix: default-gems empty line

---

bin/install

This PR re-works the solution in #417 so the code does not crash.
@jmschp FYI, I think this is the correct solution.

fix: correct handling of `.default-gems` file
